[package]
name = "nuif-editor"
version = "0.1.0-alpha.1"
edition.workspace = true
license.workspace = true
repository.workspace = true
default-run = "nuif-editor"

[lib]
name = "nuif_editor"
path = "src/lib.rs"

[features]
default = []
editor-automation = ["dep:masonry_testing"]

[[bin]]
name = "nuif-editor"
path = "src/main.rs"

[[bin]]
name = "nuif-editor-app"
path = "src/bin/editor-app.rs"

[[bin]]
name = "nuif-editor-automation"
path = "src/bin/editor-automation.rs"
required-features = ["editor-automation"]

[dependencies]
masonry = { version = "0.4.0", git = "https://github.com/refpath/xilem.git", rev = "1b96eb8db3f88f85db1a3594d80d3480b29392fb" }
masonry_testing = { version = "0.4.0", git = "https://github.com/refpath/xilem.git", rev = "1b96eb8db3f88f85db1a3594d80d3480b29392fb", optional = true }
masonry_winit = { version = "0.4.0", git = "https://github.com/refpath/xilem.git", rev = "1b96eb8db3f88f85db1a3594d80d3480b29392fb" }
nuif-adapter = { version = "0.0.1", path = "../../crates/nuif-adapter" }
nuif-api = { version = "0.0.0", path = "../../crates/nuif-api" }
nuif-codec = { version = "0.0.0", path = "../../crates/nuif-codec" }
nuif-core = { version = "0.0.1", path = "../../crates/nuif-core" }
nuif-dtcg = { version = "0.0.1", path = "../../crates/nuif-dtcg" }
nuif-html = { version = "0.0.1", path = "../../crates/nuif-html" }
nuif-layout = { version = "0.0.0", path = "../../crates/nuif-layout" }
nuif-protocol = { version = "0.0.1", path = "../../crates/nuif-protocol" }
nuif-render = { version = "0.0.0", path = "../../crates/nuif-render" }
nuif-svg = { version = "0.0.1", path = "../../crates/nuif-svg" }
nuif-text = { version = "0.0.1", path = "../../crates/nuif-text" }
rfd = "0.17.2"
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
tracing = "0.1"

[dev-dependencies]
masonry_testing = { version = "0.4.0", git = "https://github.com/refpath/xilem.git", rev = "1b96eb8db3f88f85db1a3594d80d3480b29392fb" }
nuif-testing = { version = "0.0.1", path = "../../crates/nuif-testing" }

[lints]
workspace = true
