[package]
name = "nuif-editor"
version = "0.0.1"
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "nuif_editor"
path = "src/lib.rs"

[features]
default = []
editor-automation = ["dep:masonry_testing"]

[[bin]]
name = "nuif-editor"
path = "src/main.rs"

[[bin]]
name = "nuif-editor-automation"
path = "src/bin/editor-automation.rs"
required-features = ["editor-automation"]

[dependencies]
masonry = { git = "https://github.com/linebender/xilem.git", rev = "b81d8d7a631849def6eeab282561439b963862e5" }
masonry_testing = { git = "https://github.com/linebender/xilem.git", rev = "b81d8d7a631849def6eeab282561439b963862e5", optional = true }
masonry_winit = { git = "https://github.com/linebender/xilem.git", rev = "b81d8d7a631849def6eeab282561439b963862e5" }
nuif-api = { path = "../../crates/nuif-api" }
nuif-codec = { path = "../../crates/nuif-codec" }
nuif-core = { path = "../../crates/nuif-core" }
nuif-layout = { path = "../../crates/nuif-layout" }
nuif-protocol = { path = "../../crates/nuif-protocol" }
nuif-render = { path = "../../crates/nuif-render" }
nuif-text = { path = "../../crates/nuif-text" }
rfd = "0.17.2"
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
tracing = "0.1"

[dev-dependencies]
masonry_testing = { git = "https://github.com/linebender/xilem.git", rev = "b81d8d7a631849def6eeab282561439b963862e5" }
nuif-testing = { path = "../../crates/nuif-testing" }

[lints]
workspace = true
