[package]
name = "nuif-font"
version = "0.0.1"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
nuif-core = { version = "0.0.1", path = "../nuif-core" }
serde.workspace = true
thiserror.workspace = true
ttf-parser.workspace = true

[dev-dependencies]
font-test-data.workspace = true

[lints]
workspace = true
