[package]
name = "nuif-layout"
version = "0.0.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
nuif-core = { version = "0.0.1", path = "../nuif-core" }
nuif-text = { version = "0.0.1", path = "../nuif-text" }
serde.workspace = true

[lints]
workspace = true
