[package]
name = "nuif-testing"
version = "0.0.1"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
ciborium.workspace = true
nuif-api = { path = "../nuif-api" }
nuif-codec = { path = "../nuif-codec" }
nuif-core = { path = "../nuif-core" }
nuif-layout = { path = "../nuif-layout" }
nuif-protocol = { path = "../nuif-protocol" }
nuif-render = { path = "../nuif-render" }
serde.workspace = true
serde_json.workspace = true
stats_alloc.workspace = true
taffy.workspace = true

[lints]
workspace = true
