[package]
name = "nuif-testing"
version = "0.0.1"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
ciborium.workspace = true
font-test-data.workspace = true
nuif-api = { version = "0.0.0", path = "../nuif-api" }
nuif-capture = { version = "0.0.1", path = "../nuif-capture" }
nuif-codec = { version = "0.0.0", path = "../nuif-codec" }
nuif-core = { version = "0.0.1", path = "../nuif-core" }
nuif-dtcg = { version = "0.0.1", path = "../nuif-dtcg" }
nuif-font = { version = "0.0.1", path = "../nuif-font" }
nuif-html = { version = "0.0.1", path = "../nuif-html" }
nuif-layout = { version = "0.0.0", path = "../nuif-layout" }
nuif-media = { version = "0.0.1", path = "../nuif-media" }
nuif-package = { version = "0.0.1", path = "../nuif-package" }
nuif-penpot = { version = "0.0.1", path = "../nuif-penpot" }
nuif-protocol = { version = "0.0.1", path = "../nuif-protocol" }
nuif-reconstruct = { version = "0.0.1", path = "../nuif-reconstruct" }
nuif-react = { version = "0.0.1", path = "../nuif-react" }
nuif-render = { version = "0.0.0", path = "../nuif-render" }
nuif-svg = { version = "0.0.1", path = "../nuif-svg" }
nuif-svelte = { version = "0.0.1", path = "../nuif-svelte" }
nuif-text = { version = "0.0.1", path = "../nuif-text" }
png.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
skrifa.workspace = true
stats_alloc.workspace = true
taffy.workspace = true
zip.workspace = true
zune-png.workspace = true

[lints]
workspace = true
