[package]
name = "nuif-testing"
version = "0.0.1"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
ciborium.workspace = true
nuif-api = { version = "0.0.0", path = "../nuif-api" }
nuif-codec = { version = "0.0.0", path = "../nuif-codec" }
nuif-core = { version = "0.0.1", path = "../nuif-core" }
nuif-dtcg = { version = "0.0.1", path = "../nuif-dtcg" }
nuif-html = { version = "0.0.1", path = "../nuif-html" }
nuif-layout = { version = "0.0.0", path = "../nuif-layout" }
nuif-penpot = { version = "0.0.1", path = "../nuif-penpot" }
nuif-protocol = { version = "0.0.1", path = "../nuif-protocol" }
nuif-render = { version = "0.0.0", path = "../nuif-render" }
nuif-svg = { version = "0.0.1", path = "../nuif-svg" }
nuif-text = { version = "0.0.1", path = "../nuif-text" }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
stats_alloc.workspace = true
taffy.workspace = true

[lints]
workspace = true
