/* nuif-ffi-0; experimental, byte-oriented and not ABI-stable.
 * One thread may access a given NuifFfiDocument handle at a time. Independent
 * handles and Rust-owned result buffers may be used or freed on other threads.
 */


#ifndef NUIF_FFI_H
#define NUIF_FFI_H

/* Generated by pinned cbindgen 0.29.4. Edit Rust declarations or bindings/cbindgen.toml, then run cargo xtask ffi-header. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#define NUIF_FFI_API_PROFILE "nuif-ffi-0"
#define NUIF_FFI_ENCODING_TEXT 0u
#define NUIF_FFI_ENCODING_CBOR 1u
#define NUIF_FFI_PACKAGE_PORTABLE 0u
#define NUIF_FFI_PACKAGE_AUTHORING 1u

#define NUIF_FFI_OK 0u
#define NUIF_FFI_INVALID_ARGUMENT 1u
#define NUIF_FFI_INPUT_LIMIT 2u
#define NUIF_FFI_DECODE 3u
#define NUIF_FFI_VALIDATION 4u
#define NUIF_FFI_OPERATION 5u
#define NUIF_FFI_OUTPUT_LIMIT 6u
#define NUIF_FFI_PANIC 255u


/*
 Opaque document handle. Its fields are never part of the C contract.
 */
typedef struct NuifFfiDocument NuifFfiDocument;

/*
 A Rust-owned byte buffer returned by the ABI.

 Call [`nuif_ffi_buffer_free`] exactly once for a non-empty buffer. A null
 pointer with zero length and capacity represents an empty buffer.
 */
typedef struct {
  uint8_t *ptr;
  size_t len;
  size_t capacity;
} NuifFfiBuffer;

/*
 Returned error value. The message is UTF-8 and must be released with
 [`nuif_ffi_error_free`].
 */
typedef struct {
  uint32_t code;
  NuifFfiBuffer message;
} NuifFfiError;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/*
 Frees a buffer returned by this ABI. Passing an empty buffer is a no-op.

 # Safety
 `buffer` must have been returned by this library and must not have been
 freed previously.
 */
void nuif_ffi_buffer_free(NuifFfiBuffer buffer);

/*
 Returns the ABI profile/version record as UTF-8 JSON.

 # Safety
 `out` must point to writable buffer storage.
 */
NuifFfiError nuif_ffi_capabilities(NuifFfiBuffer *out);

/*
 Applies a bounded JSON patch atomically and returns the new canonical hash.

 # Safety
 `document` must be a live, uniquely owned handle; `patch` must reference
 `len` readable bytes (unless zero); and `out` must point to writable buffer
 storage.
 */
NuifFfiError nuif_ffi_document_apply_patch(NuifFfiDocument *document,
                                           const uint8_t *patch,
                                           size_t len,
                                           NuifFfiBuffer *out);

/*
 Returns the canonical semantic document hash as UTF-8 bytes.

 # Safety
 `document` must be a live handle and `out` must point to writable buffer
 storage.
 */
NuifFfiError nuif_ffi_document_canonical_hash(const NuifFfiDocument *document, NuifFfiBuffer *out);

/*
 Exports a canonical bare document into a caller-owned buffer.

 Encoding values are `0` for canonical text and `1` for deterministic CBOR.

 # Safety
 `document` must be a live handle and `out` must point to writable buffer
 storage.
 */
NuifFfiError nuif_ffi_document_export(const NuifFfiDocument *document,
                                      uint32_t encoding_value,
                                      NuifFfiBuffer *out);

/*
 Exports a deterministic package while retaining loaded resource bytes.

 Package mode values are `0` for portable and `1` for authoring.

 # Safety
 `document` must be a live handle and `out` must point to writable buffer
 storage. The same handle must not be accessed concurrently.
 */
NuifFfiError nuif_ffi_document_export_package(const NuifFfiDocument *document,
                                              uint32_t mode_value,
                                              NuifFfiBuffer *out);

/*
 Releases a document handle. A null handle is a no-op.

 # Safety
 `document` must be null or a handle returned by this library that has not
 already been released.
 */
void nuif_ffi_document_free(NuifFfiDocument *document);

/*
 Loads a canonical bare document into an opaque handle.

 Encoding values are `0` for canonical text and `1` for deterministic CBOR.

 # Safety
 `bytes` must reference `len` readable bytes (unless `len` is zero), and
 `out` must point to writable handle storage.
 */
NuifFfiError nuif_ffi_document_load(const uint8_t *bytes,
                                    size_t len,
                                    uint32_t encoding_value,
                                    NuifFfiDocument **out);

/*
 Structurally loads a deterministic NUIF package into an opaque handle.

 A package that declares required capabilities remains available for inert
 inspection and same-mode export. Evaluation and mutation stay disabled
 until [`nuif_ffi_document_require_package_capabilities`] succeeds.

 # Safety
 `bytes` must reference `len` readable bytes (unless `len` is zero), and
 `out` must point to writable handle storage.
 */
NuifFfiError nuif_ffi_document_load_package(const uint8_t *bytes,
                                            size_t len,
                                            NuifFfiDocument **out);

/*
 Reports a package's exact required, supported-required and missing sets.
 A bare document returns JSON `null`.

 # Safety
 `document` must be a live, non-concurrently accessed handle;
 `capabilities_json` must reference a bounded UTF-8 JSON string array; and
 `out` must point to writable buffer storage.
 */
NuifFfiError nuif_ffi_document_package_capability_report(const NuifFfiDocument *document,
                                                         const uint8_t *capabilities_json,
                                                         size_t capabilities_len,
                                                         NuifFfiBuffer *out);

/*
 Authorizes a loaded package when the supplied capability set covers every
 manifest requirement. A failed call leaves the document unauthorized.

 # Safety
 `document` must be a live, uniquely owned handle and
 `capabilities_json` must reference a bounded UTF-8 JSON string array.
 */
NuifFfiError nuif_ffi_document_require_package_capabilities(NuifFfiDocument *document,
                                                            const uint8_t *capabilities_json,
                                                            size_t capabilities_len);

/*
 Evaluates and rasterizes a document or authorized package and returns the
 transport-neutral snapshot report as UTF-8 JSON.

 The report contains a SHA-256 commitment to the exact RGBA bytes rather
 than transferring the potentially large raster across this call.

 # Safety
 `document` must be a live, non-concurrently accessed handle and `out` must
 point to writable buffer storage.
 */
NuifFfiError nuif_ffi_document_snapshot_report(const NuifFfiDocument *document,
                                               double width,
                                               double height,
                                               NuifFfiBuffer *out);

/*
 Serializes structural validation diagnostics as UTF-8 JSON.

 # Safety
 `document` must be a live handle and `out` must point to writable buffer
 storage.
 */
NuifFfiError nuif_ffi_document_validate(const NuifFfiDocument *document, NuifFfiBuffer *out);

/*
 Frees the message owned by an error value. Passing a success value is safe.

 # Safety
 `error` must not be used after this call; its message must have come from
 this library and must not have been released previously.
 */
void nuif_ffi_error_free(NuifFfiError error);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* NUIF_FFI_H */
