[package]
name = "nuif-package"
version = "0.0.1"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
nuif-codec = { version = "0.0.0", path = "../nuif-codec" }
nuif-core = { version = "0.0.1", path = "../nuif-core" }
nuif-font = { version = "0.0.1", path = "../nuif-font" }
serde.workspace = true
sha2.workspace = true
base16ct.workspace = true
thiserror.workspace = true

[dev-dependencies]
font-test-data.workspace = true
zip.workspace = true

[lints]
workspace = true
